language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-26"

script:
  - ./gradlew test build
  - ./gradlew assemble